### ISSUE TITLE
Dependency on rust-crypto

### ISSUE THREAD

**Issue by cytadela8** [PumpkinSeed/eip55-rs#2]
This library depends on unmaintained and vulnerable rust-crypto. This probably doesn't introduce any security issue, but it would be nice to replace it with something modern like sha3 crate from RustCryptoOrg.

https://rustsec.org/advisories/RUSTSEC-2016-0005.html
https://rustsec.org/advisories/RUSTSEC-2022-0011.html

**Comment by PumpkinSeed** [comment]
Sorry for the late reply, I just changed the package to use sha3 crate. Thanks for the report.

**Comment by PumpkinSeed** [comment]
I released v0.2.0 to crates.io which has this update.
