### ISSUE TITLE
`checksum()` panics

### ISSUE THREAD

**Issue by perama-v** [PumpkinSeed/eip55-rs#5]
## Describe the bug

When passing a string without a prefix, the `checksum()` function fails. 

The function accepts both prefixed and non-prefixed strings. However, indexing for characters is performed without taking this into account. This results in a panic during execution.

**Comment by PumpkinSeed** [comment]
Released to crates.io, v0.3.0

**Comment by PumpkinSeed** [comment]
Thanks for the contribution.
